---
kind: pipeline
name: default
type: docker

platform:
  os: linux
  arch: arm64

steps:
  - name: build-13
    image: ghcr.io/codestation/drone-docker
    settings:
      repos:
        - registry.megpoid.xyz/codestation/postgres
      tags: 13
      dockerfile: 13/Dockerfile
      registry: registry.megpoid.xyz
      platforms:
        - linux/amd64
        - linux/arm64
      buildkit: true
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password

  - name: build-14
    image: ghcr.io/codestation/drone-docker
    settings:
      repos:
        - registry.megpoid.xyz/codestation/postgres
      tags: 14
      dockerfile: 14/Dockerfile
      registry: registry.megpoid.xyz
      platforms:
        - linux/amd64
        - linux/arm64
      buildkit: true
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password

  - name: update
    image: plugins/webhook
    settings:
      urls: http://updater:8000/apis/swarm/v1/update
      token_value:
        from_secret: updater_appkey
      template: |
        {
          "images": [
            "registry.megpoid.xyz/codestation/postgres"
          ]
        }

trigger:
  branch:
    - master
