---
kind: pipeline
name: default
type: kubernetes

platform:
  os: linux
  arch: arm64

steps:
  - name: build-14
    image: ghcr.io/codestation/drone-kaniko
    settings:
      registry: registry.megpoid.dev
      repo: registry.megpoid.dev/codestation/postgres
      dockerfile: 14/Dockerfile
      tags:
        - 14
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password

  - name: build-16
    image: ghcr.io/codestation/drone-kaniko
    settings:
      registry: registry.megpoid.dev
      repo: registry.megpoid.dev/codestation/postgres
      dockerfile: 16/Dockerfile
      tags:
        - 16
        - latest
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password

trigger:
  branch:
    - master
