---
kind: pipeline
name: default
type: kubernetes

platform:
  os: linux
  arch: arm64

steps:
  - name: build
    image: ghcr.io/codestation/drone-kaniko
    settings:
      repos:
        - registry.megpoid.dev/codestation/postgres
      tags:
        - 14
        - latest
      dockerfile: 14/Dockerfile
      registry: registry.megpoid.dev
      platforms:
        - linux/amd64
        - linux/arm64
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password

trigger:
  branch:
    - master
