apiVersion: v1
kind: Secret
metadata:
  name: postgres-root-credentials
  labels:
    app.kubernetes.io/name: postgres
    app.kubernetes.io/instance: postgres
type: kubernetes.io/basic-auth
stringData:
  username: postgres
  password: my_secret_password
