matrix:
  POSTGRES_VERSION:
    - 17

steps:
  build:
    image: woodpeckerci/plugin-docker-buildx:6.0.1
    settings:
      registry: registry.megpoid.dev
      repo: registry.megpoid.dev/codestation/postgres
      dockerfile: ${POSTGRES_VERSION}/Dockerfile
      tags:
        - latest
        - ${POSTGRES_VERSION}
      config:
        from_secret: registry_credentials

when:
  event:
    - push
    - manual
  branch:
    - master
