apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-scripts
data:
  init-database.sh: |
    #!/bin/bash
    set -eu

    # exit if POSTGRES_DB_USER nor POSTGRES_DB_PASSWORD are set
    if [ -z "${POSTGRES_DB_USER}" ] || [ -z "${POSTGRES_DB_PASSWORD}" ]; then
      echo "POSTGRES_DB_USER and POSTGRES_DB_PASSWORD must be set"
      exit 1
    fi

    psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "${POSTGRES_DB:-POSTGRES_USER}" <<-EOSQL
      CREATE USER $POSTGRES_DB_USER WITH PASSWORD '$POSTGRES_DB_PASSWORD';
      CREATE DATABASE $POSTGRES_DB_NAME OWNER $POSTGRES_DB_USER;
    EOSQL
