name: Docker

on:
  push:
    branches: [ master ]
  schedule:
    - cron: "00 1 * * 0"

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: codestation/postgres

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log into registry ${{ env.REGISTRY }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push Docker image (postgres:13)
        uses: docker/build-push-action@v2
        with:
          push: ${{ github.event_name != 'pull_request' }}
          platforms: linux/amd64,linux/arm64
          file: 13/Dockerfile
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:13
          labels: ${{ steps.meta.outputs.labels }}

      - name: Build and push Docker image (postgres:14)
        uses: docker/build-push-action@v2
        with:
          push: ${{ github.event_name != 'pull_request' }}
          platforms: linux/amd64,linux/arm64
          file: 14/Dockerfile
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:14
          labels: ${{ steps.meta.outputs.labels }}
